version: '3.4'

services:
  acadev:
    image: new-acadev
    depends_on:
      - db
    build:
      context: .
      dockerfile: AcaDev/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "11@@22WW33ee"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"